syntax = "proto3";

package users.reviews;

import "google/protobuf/timestamp.proto";

enum ReviewEventType {
  UNSPECIFIED = 0;
  CREATED = 1;
  EDITED = 2;
  LIKED = 3;
  COMMENTED = 4;
}

message ReviewEvent {

  string event_id = 1;

  string review_id = 2;
  string user_id = 3;
  string created_at = 4;
  string updated_at = 5;

  ReviewEventType type = 6;

  // Поля для типов CREATE, EDIT
  string text = 7;
  string new_text = 8;
  repeated string pics_urls = 9;

  // Поле для COMMENT
  string comment = 10;

  google.protobuf.Timestamp event_time = 11;
}
