syntax = "proto3";

package reviews.events;

import "google/protobuf/timestamp.proto";

enum ReviewEventType {
  UNSPECIFIED = 0;
  REVIEW_CREATED = 1;
  REVIEW_UPDATED = 2;
  REVIEW_DELETED = 3;
}

message ReviewEvent {

  string event_id = 1;
  ReviewEventType type = 2;
  google.protobuf.Timestamp event_time = 3;

  string review_id = 4;
  string user_id = 5;

  string text = 6;
  repeated string pics_urls = 7;

  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}
